export const IATA_HE: Record<string, string> = {
  TLV: "תל אביב",
  LON: "לונדון",
  LHR: "לונדון",
  LGW: "לונדון",
  STN: "לונדון",
  NYC: "ניו יורק",
  JFK: "ניו יורק",
  EWR: "ניו יורק",
  LGA: "ניו יורק",
  PFO: "פאפוס",
  LCA: "לרנקה",
  HER: "הרקליון",
  RHO: "רודוס",
  SKG: "סלוניקי",
  ATH: "אתונה",
  TIA: "טירנה",
  CDG: "פריז",
  ORY: "פריז",
  PAR: "פריז",
  BCN: "ברצלונה",
  MAD: "מדריד",
  FCO: "רומא",
  MXP: "מילאנו",
  MIL: "מילאנו",
  AMS: "אמסטרדם",
  FRA: "פרנקפורט",
  MUC: "מינכן",
  BER: "ברלין",
  VIE: "וינה",
  ZRH: "ציריך",
  PRG: "פראג",
  BUD: "בודפשט",
  IST: "איסטנבול",
  DXB: "דובאי",
  BKK: "בנגקוק",
  PHK: "פוקט",
  HKT: "פוקט",
  DEL: "דלהי",
  BOM: "מומבאי",
  SOF: "סופיה",
  BTS: "ברטיסלבה",
  WAW: "ורשה",
  KRK: "קרקוב",
  TBS: "טביליסי",
  EVN: "ירוואן",
  BOJ: "בורגס",
  VAR: "ורנה",
  SPU: "ספליט",
  DBV: "דוברובניק",
  ZAG: "זאגרב",
  TFS: "טנריף",
  AYT: "אנטליה",
};

export function destinationHe(code: string | null | undefined): string {
  if (!code) return "";
  const c = code.trim().toUpperCase();
  return IATA_HE[c] ?? c;
}