/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteTravelRequirementsRouteImport } from './routes/_site.travel-requirements'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as SiteServicesRouteImport } from './routes/_site.services'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SiteInsuranceRouteImport } from './routes/_site.insurance'
import { Route as SiteDealsRouteImport } from './routes/_site.deals'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteAccessibilityRouteImport } from './routes/_site.accessibility'
import { Route as AppTelegramRouteImport } from './routes/_app.telegram'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppIntakeRouteImport } from './routes/_app.intake'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppFlightsRouteImport } from './routes/_app.flights'
import { Route as AppEmailIngestRouteImport } from './routes/_app.email-ingest'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as ApiPublicParseDealRouteImport } from './routes/api.public.parse-deal'
import { Route as AppCustomersIdRouteImport } from './routes/_app.customers.$id'
import { Route as ApiPublicTelegramPollRouteImport } from './routes/api.public.telegram.poll'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTravelRequirementsRoute = SiteTravelRequirementsRouteImport.update({
  id: '/travel-requirements',
  path: '/travel-requirements',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteInsuranceRoute = SiteInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDealsRoute = SiteDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAccessibilityRoute = SiteAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => SiteRoute,
} as any)
const AppTelegramRoute = AppTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeRoute = AppIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppFlightsRoute = AppFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailIngestRoute = AppEmailIngestRouteImport.update({
  id: '/email-ingest',
  path: '/email-ingest',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicParseDealRoute = ApiPublicParseDealRouteImport.update({
  id: '/api/public/parse-deal',
  path: '/api/public/parse-deal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicTelegramPollRoute = ApiPublicTelegramPollRouteImport.update({
  id: '/api/public/telegram/poll',
  path: '/api/public/telegram/poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/email-ingest': typeof AppEmailIngestRoute
  '/flights': typeof AppFlightsRoute
  '/import': typeof AppImportRoute
  '/intake': typeof AppIntakeRoute
  '/leads': typeof AppLeadsRoute
  '/payments': typeof AppPaymentsRoute
  '/tasks': typeof AppTasksRoute
  '/telegram': typeof AppTelegramRoute
  '/accessibility': typeof SiteAccessibilityRoute
  '/contact': typeof SiteContactRoute
  '/deals': typeof SiteDealsRoute
  '/insurance': typeof SiteInsuranceRoute
  '/privacy': typeof SitePrivacyRoute
  '/services': typeof SiteServicesRoute
  '/terms': typeof SiteTermsRoute
  '/travel-requirements': typeof SiteTravelRequirementsRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/api/public/parse-deal': typeof ApiPublicParseDealRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/email-ingest': typeof AppEmailIngestRoute
  '/flights': typeof AppFlightsRoute
  '/import': typeof AppImportRoute
  '/intake': typeof AppIntakeRoute
  '/leads': typeof AppLeadsRoute
  '/payments': typeof AppPaymentsRoute
  '/tasks': typeof AppTasksRoute
  '/telegram': typeof AppTelegramRoute
  '/accessibility': typeof SiteAccessibilityRoute
  '/contact': typeof SiteContactRoute
  '/deals': typeof SiteDealsRoute
  '/insurance': typeof SiteInsuranceRoute
  '/privacy': typeof SitePrivacyRoute
  '/services': typeof SiteServicesRoute
  '/terms': typeof SiteTermsRoute
  '/travel-requirements': typeof SiteTravelRequirementsRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/api/public/parse-deal': typeof ApiPublicParseDealRoute
  '/customers': typeof AppCustomersIndexRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/email-ingest': typeof AppEmailIngestRoute
  '/_app/flights': typeof AppFlightsRoute
  '/_app/import': typeof AppImportRoute
  '/_app/intake': typeof AppIntakeRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/telegram': typeof AppTelegramRoute
  '/_site/accessibility': typeof SiteAccessibilityRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/deals': typeof SiteDealsRoute
  '/_site/insurance': typeof SiteInsuranceRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/travel-requirements': typeof SiteTravelRequirementsRoute
  '/_site/': typeof SiteIndexRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/api/public/parse-deal': typeof ApiPublicParseDealRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/documents'
    | '/email-ingest'
    | '/flights'
    | '/import'
    | '/intake'
    | '/leads'
    | '/payments'
    | '/tasks'
    | '/telegram'
    | '/accessibility'
    | '/contact'
    | '/deals'
    | '/insurance'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/travel-requirements'
    | '/customers/$id'
    | '/api/public/parse-deal'
    | '/customers/'
    | '/api/public/telegram/poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/documents'
    | '/email-ingest'
    | '/flights'
    | '/import'
    | '/intake'
    | '/leads'
    | '/payments'
    | '/tasks'
    | '/telegram'
    | '/accessibility'
    | '/contact'
    | '/deals'
    | '/insurance'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/travel-requirements'
    | '/customers/$id'
    | '/api/public/parse-deal'
    | '/customers'
    | '/api/public/telegram/poll'
  id:
    | '__root__'
    | '/_app'
    | '/_site'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/email-ingest'
    | '/_app/flights'
    | '/_app/import'
    | '/_app/intake'
    | '/_app/leads'
    | '/_app/payments'
    | '/_app/tasks'
    | '/_app/telegram'
    | '/_site/accessibility'
    | '/_site/contact'
    | '/_site/deals'
    | '/_site/insurance'
    | '/_site/privacy'
    | '/_site/services'
    | '/_site/terms'
    | '/_site/travel-requirements'
    | '/_site/'
    | '/_app/customers/$id'
    | '/api/public/parse-deal'
    | '/_app/customers/'
    | '/api/public/telegram/poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicParseDealRoute: typeof ApiPublicParseDealRoute
  ApiPublicTelegramPollRoute: typeof ApiPublicTelegramPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/travel-requirements': {
      id: '/_site/travel-requirements'
      path: '/travel-requirements'
      fullPath: '/travel-requirements'
      preLoaderRoute: typeof SiteTravelRequirementsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/insurance': {
      id: '/_site/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof SiteInsuranceRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/deals': {
      id: '/_site/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof SiteDealsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/accessibility': {
      id: '/_site/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof SiteAccessibilityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_app/telegram': {
      id: '/_app/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof AppTelegramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake': {
      id: '/_app/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AppIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flights': {
      id: '/_app/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof AppFlightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email-ingest': {
      id: '/_app/email-ingest'
      path: '/email-ingest'
      fullPath: '/email-ingest'
      preLoaderRoute: typeof AppEmailIngestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/parse-deal': {
      id: '/api/public/parse-deal'
      path: '/api/public/parse-deal'
      fullPath: '/api/public/parse-deal'
      preLoaderRoute: typeof ApiPublicParseDealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/telegram/poll': {
      id: '/api/public/telegram/poll'
      path: '/api/public/telegram/poll'
      fullPath: '/api/public/telegram/poll'
      preLoaderRoute: typeof ApiPublicTelegramPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmailIngestRoute: typeof AppEmailIngestRoute
  AppFlightsRoute: typeof AppFlightsRoute
  AppImportRoute: typeof AppImportRoute
  AppIntakeRoute: typeof AppIntakeRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTelegramRoute: typeof AppTelegramRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmailIngestRoute: AppEmailIngestRoute,
  AppFlightsRoute: AppFlightsRoute,
  AppImportRoute: AppImportRoute,
  AppIntakeRoute: AppIntakeRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTelegramRoute: AppTelegramRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SiteRouteChildren {
  SiteAccessibilityRoute: typeof SiteAccessibilityRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteDealsRoute: typeof SiteDealsRoute
  SiteInsuranceRoute: typeof SiteInsuranceRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteTravelRequirementsRoute: typeof SiteTravelRequirementsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAccessibilityRoute: SiteAccessibilityRoute,
  SiteContactRoute: SiteContactRoute,
  SiteDealsRoute: SiteDealsRoute,
  SiteInsuranceRoute: SiteInsuranceRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteTravelRequirementsRoute: SiteTravelRequirementsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicParseDealRoute: ApiPublicParseDealRoute,
  ApiPublicTelegramPollRoute: ApiPublicTelegramPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
