/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelRequirementsRouteImport } from './routes/travel-requirements'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTelegramRouteImport } from './routes/_app.telegram'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppIntakeRouteImport } from './routes/_app.intake'
import { Route as AppFlightsRouteImport } from './routes/_app.flights'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppCustomersIdRouteImport } from './routes/_app.customers.$id'
import { Route as ApiPublicTelegramPollRouteImport } from './routes/api.public.telegram.poll'

const TravelRequirementsRoute = TravelRequirementsRouteImport.update({
  id: '/travel-requirements',
  path: '/travel-requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTelegramRoute = AppTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeRoute = AppIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppFlightsRoute = AppFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicTelegramPollRoute = ApiPublicTelegramPollRouteImport.update({
  id: '/api/public/telegram/poll',
  path: '/api/public/telegram/poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/travel-requirements': typeof TravelRequirementsRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/flights': typeof AppFlightsRoute
  '/intake': typeof AppIntakeRoute
  '/leads': typeof AppLeadsRoute
  '/payments': typeof AppPaymentsRoute
  '/tasks': typeof AppTasksRoute
  '/telegram': typeof AppTelegramRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/travel-requirements': typeof TravelRequirementsRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/flights': typeof AppFlightsRoute
  '/intake': typeof AppIntakeRoute
  '/leads': typeof AppLeadsRoute
  '/payments': typeof AppPaymentsRoute
  '/tasks': typeof AppTasksRoute
  '/telegram': typeof AppTelegramRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers': typeof AppCustomersIndexRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/travel-requirements': typeof TravelRequirementsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/flights': typeof AppFlightsRoute
  '/_app/intake': typeof AppIntakeRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/telegram': typeof AppTelegramRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/travel-requirements'
    | '/dashboard'
    | '/documents'
    | '/flights'
    | '/intake'
    | '/leads'
    | '/payments'
    | '/tasks'
    | '/telegram'
    | '/customers/$id'
    | '/customers/'
    | '/api/public/telegram/poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/travel-requirements'
    | '/dashboard'
    | '/documents'
    | '/flights'
    | '/intake'
    | '/leads'
    | '/payments'
    | '/tasks'
    | '/telegram'
    | '/customers/$id'
    | '/customers'
    | '/api/public/telegram/poll'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/travel-requirements'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/flights'
    | '/_app/intake'
    | '/_app/leads'
    | '/_app/payments'
    | '/_app/tasks'
    | '/_app/telegram'
    | '/_app/customers/$id'
    | '/_app/customers/'
    | '/api/public/telegram/poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  TravelRequirementsRoute: typeof TravelRequirementsRoute
  ApiPublicTelegramPollRoute: typeof ApiPublicTelegramPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel-requirements': {
      id: '/travel-requirements'
      path: '/travel-requirements'
      fullPath: '/travel-requirements'
      preLoaderRoute: typeof TravelRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/telegram': {
      id: '/_app/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof AppTelegramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake': {
      id: '/_app/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AppIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flights': {
      id: '/_app/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof AppFlightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/telegram/poll': {
      id: '/api/public/telegram/poll'
      path: '/api/public/telegram/poll'
      fullPath: '/api/public/telegram/poll'
      preLoaderRoute: typeof ApiPublicTelegramPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFlightsRoute: typeof AppFlightsRoute
  AppIntakeRoute: typeof AppIntakeRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTelegramRoute: typeof AppTelegramRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFlightsRoute: AppFlightsRoute,
  AppIntakeRoute: AppIntakeRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTelegramRoute: AppTelegramRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  TravelRequirementsRoute: TravelRequirementsRoute,
  ApiPublicTelegramPollRoute: ApiPublicTelegramPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
